---
- hosts: localhost
  sudo: yes
  gather_facts: no

  tasks:
  - name: ensure apt cache is up to date
    apt: update_cache=yes
  - name: ensure packages are installed
    apt: name={{item}}
    with_items:
        - git
        - bzr
        - mercurial
        - postgresql-9.4
        - python-psycopg2

  - name: change postgresql default mode
    template: src=templates/pg_hba.conf.j2 dest=/etc/postgresql/9.4/main/pg_hba.conf owner=postgres group=postgres mode=0644
  - name: restart
    service: name=postgresql state=reloaded

- hosts: localhost
  sudo: yes
  sudo_user: postgres
  gather_facts: no

  vars:
    dbname: ubuntu
    dbuser: ubuntu
    dbpassword: wercker

  tasks:
  - name: ensure database is created
    postgresql_db: name={{dbname}}

  - name: ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

  - name: ensure user does not have unnecessary privilege
    postgresql_user: name={{dbuser}} role_attr_flags=CREATEDB,CREATEROLE,SUPERUSER