---
- hosts: localhost
  sudo: yes
  gather_facts: no

  tasks:
  - name: ensure apt cache is up to date
    apt: update_cache=yes
  - name: ensure packages are installed
    apt: name={{item}}
    with_items:
        - git
        - bzr
        - mercurial
        - postgresql
        - python-psycopg2

- hosts: localhost
  sudo: yes
  sudo_user: postgres
  gather_facts: no

  vars:
    dbuser: wercker
    dbpassword: mysupersecretpassword

  tasks:
  - name: ensure user has access to database
    postgresql_user: name={{dbuser}} password={{dbpassword}}